language: java
java:
    - "java"

language: node_js
node_js:
    - "stable"
cache:
  directories:
    - organized/node_modules
before_script:
    - cd /organized/src/Backend
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - cd /organized
    - npm install
script:
    - make
    - mvn test -B
    - npm test
